	-- Creación tablas dimensionales 
	DROP TABLE DIM_BANCOS

	CREATE TABLE DIM_BANCOS (
	COD_ENTIDAD CHAR(5) NOT NULL,
	BANCO VARCHAR(100) NOT NULL,
	PRIMARY KEY (COD_ENTIDAD));


	CREATE TABLE DIM_UBIGEO (
	COD_UBIGEO CHAR(6) NOT NULL,
	DEPARTAMENTO VARCHAR(15) NOT NULL,
	PROVINCIA VARCHAR(30) NOT NULL,
	DISTRITO VARCHAR(50) NOT NULL,
	ZONA CHAR(4) NOT NULL,
	CIUDAD_IMP VARCHAR(20) NOT NULL,
	PRIMARY KEY (COD_UBIGEO));


	CREATE TABLE DIM_ONPE (
	COD_NUMDOC VARCHAR(8) NOT NULL,
	COD_UBIGEO CHAR(6) NULL,
	SEXO VARCHAR(10) NULL,
	EDAD NUMBER,
	PRIMARY KEY (COD_NUMDOC));


	CREATE TABLE DIM_CLIENTES (
	PERIODO NUMBER(6) NOT NULL,
	COD_SBS_CLI NUMBER NOT NULL,
	COD_NUMDOC VARCHAR(8) NULL,
	TIP_DOC VARCHAR(40) NULL,
	SEGMENTO VARCHAR(60) NOT NULL,
	CALIFICACION VARCHAR(30) NOT NULL, 
	PRIMARY KEY (PERIODO, COD_SBS_CLI));


	CREATE TABLE FACT_SALDOSRCC
	(PERIODO NUMBER(6),
	CODCLIENTESBS NUMBER,
	CODENTIDADFINANCIERA CHAR(5),
	MTOSALDORCC NUMBER(16,2),
	SUBPRODUCTO NUMBER,
	FECACTUALIZACIONTABLA DATE)

	CREATE TABLE DIM_SUBPRODUCTOSBS (
	CODSUBPRODUCTOSBS NUMBER ,
	CODPRODUCTOSBS NUMBER ,
	DESCODSUBPRODUCTOSBS VARCHAR2(50)
	)

	CREATE TABLE DIM_PRODUCTOSBS
	(
	CODPRODUCTOSBS NUMBER,
	DESPRODUCTOSBS VARCHAR2(50)
	)



	ALTER TABLE DIM_SUBPRODUCTOSBS
	ADD CONSTRAINT fk_PRODUCTOS_SUBPRODUCTO
	FOREIGN KEY (CODPRODUCTOSBS)
	REFERENCES DIM_PRODUCTOSBS(CODPRODUCTOSBS);

	ALTER TABLE DIM_SUBPRODUCTOSBS
	ADD CONSTRAINT SUBPRODUCTO_pk PRIMARY KEY (CODSUBPRODUCTOSBS);
	ALTER TABLE DIM_PRODUCTOSBS
	ADD CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRODUCTOSBS);

	ALTER TABLE FACT_SALDOSRCC
	ADD CONSTRAINT fk_SALDOS_PRODUCTO
	FOREIGN KEY (SUBPRODUCTO)
	REFERENCES DIM_SUBPRODUCTOSBS(CODSUBPRODUCTOSBS);

	ALTER TABLE DIM_ONPE
	ADD CONSTRAINT fk_UBIGEO_ONPE
	FOREIGN KEY (COD_UBIGEO)
	REFERENCES DIM_UBIGEO(COD_UBIGEO);

	ALTER TABLE DIM_CLIENTES
	ADD CONSTRAINT fk_CLIENTES_ONPE_DIM
	FOREIGN KEY (COD_NUMDOC)
	REFERENCES DIM_ONPE(COD_NUMDOC);

	ALTER TABLE FACT_SALDOSRCC
	ADD CONSTRAINT fk_FACTSAL_CLIENTES
	FOREIGN KEY (PERIODO,CODCLIENTESBS)
	REFERENCES DIM_CLIENTES(PERIODO,COD_SBS_CLI);

	ALTER TABLE FACT_SALDOSRCC
	ADD CONSTRAINT fk_FACTSAL_BANCOS
	FOREIGN KEY (CODENTIDADFINANCIERA)
	REFERENCES DIM_BANCOS(COD_ENTIDAD);

	ALTER TABLE FACT_SALDOSRCC
	ADD CONSTRAINT fk_SALDOS_SUBPRODUCTO
	FOREIGN KEY (SUBPRODUCTO)
	REFERENCES DIM_SUBPRODUCTOSBS(CODSUBPRODUCTOSBS);
		 